/*
 * Ex3.c
 *
 *  Created on: Sep 16, 2024
 *      Author: Admin
 */

#include "Ex3.h"
void Exercise3(void){
	HAL_GPIO_WritePin(GPIOB, GPIO_PIN_10, SET);
	HAL_GPIO_WritePin(GPIOB, GPIO_PIN_6, SET);				//D1-V2
	HAL_GPIO_WritePin(GPIOB, GPIO_PIN_2, SET);
	HAL_GPIO_WritePin(GPIOB, GPIO_PIN_8, SET);
	HAL_Delay(2000);
	HAL_GPIO_TogglePin(GPIOB, GPIO_PIN_10);
	HAL_GPIO_TogglePin(GPIOB, GPIO_PIN_6);
	HAL_GPIO_TogglePin(GPIOB, GPIO_PIN_2);
	HAL_GPIO_TogglePin(GPIOB, GPIO_PIN_8);

	HAL_GPIO_WritePin(GPIOB, GPIO_PIN_0, SET);			//X1-D2
	HAL_GPIO_WritePin(GPIOB, GPIO_PIN_4, SET);
	HAL_GPIO_WritePin(GPIOB, GPIO_PIN_1, SET);
	HAL_GPIO_WritePin(GPIOB, GPIO_PIN_7, SET);
	HAL_Delay(3000);
	HAL_GPIO_TogglePin(GPIOB, GPIO_PIN_0);
	HAL_GPIO_TogglePin(GPIOB, GPIO_PIN_4);
	HAL_GPIO_TogglePin(GPIOB, GPIO_PIN_1);
	HAL_GPIO_TogglePin(GPIOB, GPIO_PIN_7);

	HAL_GPIO_WritePin(GPIOB, GPIO_PIN_11, SET);				//V1-D2
	HAL_GPIO_WritePin(GPIOB, GPIO_PIN_5, SET);
	HAL_GPIO_WritePin(GPIOB, GPIO_PIN_1, SET);
	HAL_GPIO_WritePin(GPIOB, GPIO_PIN_7, SET);
	HAL_Delay(2000);
	HAL_GPIO_TogglePin(GPIOB, GPIO_PIN_11);
	HAL_GPIO_TogglePin(GPIOB, GPIO_PIN_5);
	HAL_GPIO_TogglePin(GPIOB, GPIO_PIN_1);
	HAL_GPIO_TogglePin(GPIOB, GPIO_PIN_7);

	HAL_GPIO_WritePin(GPIOB, GPIO_PIN_10, SET);					//D1-X2
	HAL_GPIO_WritePin(GPIOB, GPIO_PIN_6, SET);
	HAL_GPIO_WritePin(GPIOB, GPIO_PIN_3, SET);
	HAL_GPIO_WritePin(GPIOB, GPIO_PIN_9, SET);
	HAL_Delay(3000);
	HAL_GPIO_TogglePin(GPIOB, GPIO_PIN_10);
	HAL_GPIO_TogglePin(GPIOB, GPIO_PIN_6);
	HAL_GPIO_TogglePin(GPIOB, GPIO_PIN_3);
	HAL_GPIO_TogglePin(GPIOB, GPIO_PIN_9);

}
